from time import sleep
import RPi.GPIO as GPIO

GPIO.setmode(GPIO.BOARD)

currentpin = 0

GPIO.setup(3, GPIO.OUT)
GPIO.setup(5, GPIO.OUT)
GPIO.setup(11, GPIO.OUT)
GPIO.setup(8, GPIO.OUT)
GPIO.setup(10, GPIO.OUT)
GPIO.setup(18, GPIO.OUT)
GPIO.setup(22, GPIO.OUT)

while(1):
    print("Current Pin: 3")
    GPIO.output(3, GPIO.LOW)
    print("Setting pin 3 to HIGH")
    sleep(3)
    GPIO.output(3, GPIO.HIGH)
    print("Current Pin: 5")
    sleep(3)
    GPIO.output(5, GPIO.LOW)
    print("Setting pin 5 to HIGH")
    sleep(3)
    GPIO.output(5, GPIO.HIGH)
    sleep(3)
    print("Current Pin: 11")
    GPIO.output(11, GPIO.LOW)
    print("Setting pin 11 to HIGH")
    sleep(3)
    GPIO.output(11, GPIO.HIGH)
    sleep(3)
    print("Current Pin: 8")
    GPIO.output(8, GPIO.LOW)
    print("Setting pin 8 to HIGH")
    sleep(3)
    GPIO.output(8, GPIO.HIGH)
    sleep(3)
    print("Current Pin: 10")
    GPIO.output(10, GPIO.LOW)
    print("Setting pin 10 to HIGH")
    sleep(3)
    GPIO.output(10, GPIO.HIGH)
    sleep(3)
    print("Current Pin: 18")
    GPIO.output(18, GPIO.LOW)
    print("Setting pin 18 to HIGH")
    sleep(3)
    GPIO.output(18, GPIO.HIGH)
    print("Current Pin: 3")
    sleep(3)
    GPIO.output(22, GPIO.LOW)
    print("Setting pin 22 to HIGH")
    sleep(3)
    print("Current Pin: 22")
    GPIO.output(22, GPIO.HIGH)
    sleep(3)